**1. Series & DataFrame Basics**

Concept: A Series is a single labeled column of data: like one column in a spreadsheet, with row labels (an index) attached. A DataFrame is a collection of Series sharing the same index, the full spreadsheet, not just one column.

In [2]:
import pandas as pd

In [3]:
s = pd.Series([10, 20, 30])
print(s)
df = pd.DataFrame({'name': ['Ram', 'Sita'], 'age': [20, 22]})
print(df)

0    10
1    20
2    30
dtype: int64
   name  age
0   Ram   20
1  Sita   22

Key attributes:

Attribute/Method and Meaning

.index	(Row labels)

.columns	(Column names (DataFrame only))

.values	(Underlying data as a NumPy array)

.shape	   (rows, columns)

.dtypes	   (Data type of each column)

.head(n), .tail(n)	(First/last n rows)

.info()	  (Summary: columns, types, non-null counts)

**Exercise**

1. Create a Series of 5 numbers of your choice.

2. Create a DataFrame with columns city and population for 3 cities.

3. Print .shape, .columns, and .dtypes of that DataFrame

In [4]:
#1
s = pd.Series([5, 10, 15, 20, 25])

In [5]:
#2
df = pd.DataFrame({'city': ['Kathmandu', 'Pokhara', 'Biratnagar'],
                    'population': [1000000, 500000, 300000]})

In [7]:
# 3
print(df.shape)
print(df.columns)
print(df.dtypes)

(3, 2)
Index(['city', 'population'], dtype='object')
city          object
population     int64
dtype: object

**2. Reading/Creating Data (dict/list/CSV)**

Concept: DataFrames can be built directly from Python structures already in memory, or read from external files, same object, different source.

In [9]:
# from dict
df1 = pd.DataFrame({'a': [1,2], 'b': [3,4]})

# from list of lists (need column names)
df2 = pd.DataFrame([[1,3],[2,4]], columns=['a','b'])

# from CSV
df3 = pd.read_csv('data.csv')

**Key operations:**

**Function	Purpose**

pd.DataFrame(dict)	---Build from dict of lists (keys = columns)

pd.DataFrame(list, columns=)---	Build from list of rows

pd.read_csv(path)	---Load DataFrame from CSV file

pd.read_csv(path, index_col=0)	---Use first column as index

**Exercise**

1. Create a DataFrame from a dict with columns product and price (3 rows).

2. Create the same DataFrame from a list of lists instead.

3. Save it to products.csv using .to_csv(), then reload it with pd.read_csv().

In [10]:
# 1
df = pd.DataFrame({'product': ['Pen','Book','Bag'], 'price': [10, 50, 200]})

In [11]:
# 2
df2 = pd.DataFrame([['Pen',10],['Book',50],['Bag',200]], columns=['product','price'])

In [12]:
# 3
df.to_csv('products.csv', index=False)
loaded = pd.read_csv('products.csv')

**3. Indexing & Selection (loc/iloc)**

**Concept:**  .loc selects by label (the named index/column), .iloc selects by integer position — like the difference between asking for "the row named Ram" versus "the 3rd row, whatever its name is."

In [13]:
df = pd.DataFrame({'name': ['Ram','Sita','Hari'], 'age': [20,22,25]}, index=['a','b','c'])

In [14]:
df.loc['a']          # row labeled 'a' (by name)

name    Ram
age      20
Name: a, dtype: object

In [15]:
df.loc['a', 'age']   # single value by label

np.int64(20)

In [16]:
df.iloc[0]           # first row (by position)

name    Ram
age      20
Name: a, dtype: object

In [17]:
df.iloc[0, 1]        # first row, second column, by position

np.int64(20)

In [18]:
df['name']           # single column (returns a Series)

a     Ram
b    Sita
c    Hari
Name: name, dtype: object

In [19]:
df[['name','age']]   # multiple columns (returns a DataFrame)

   name  age
a   Ram   20
b  Sita   22
c  Hari   25

**Key patterns:**

**Pattern	Meaning**

df['col']---	Select one column

df[['col1','col2']]---	Select multiple columns

df.loc[label]	---Select row(s) by label

df.loc[label, col]---	Select cell by label

df.iloc[pos]	---Select row(s) by integer position

df.iloc[pos, pos]---	Select cell by position

**Exercise**

Given df = pd.DataFrame({'name':['Ram','Sita','Hari','Gita'],'score':[70,85,60,90]}, index=['a','b','c','d']):

1. Get Sita's row using .loc.

2. Get the last row using .iloc.
3. Get Hari's score only (single value).
4. Get just the name and score columns for rows b and d.

In [21]:
df = pd.DataFrame({'name':['Ram','Sita','Hari','Gita'],
                   'score':[70,85,60,90]},
                   index=['a','b','c','d'])

In [22]:
# 1
df.loc['b']

name     Sita
score      85
Name: b, dtype: object

In [23]:

# 2
df.iloc[-1]

name     Gita
score      90
Name: d, dtype: object

In [24]:
# 3
df.loc['c', 'score']

np.int64(60)

In [25]:
# 4
df.loc[['b','d'], ['name','score']]

   name  score
b  Sita     85
d  Gita     90