**4. Filtering & Boolean Masks**

**Concept:** A boolean mask is a Series of True/False values, one per row, used to keep only the rows that satisfy a condition: like a sieve that only lets matching rows through.

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({'name':['Ram','Sita','Hari'],
                   'score':[70,85,60]})

In [4]:
mask = df['score'] > 65
print(mask)                   # True/False per row

0     True
1     True
2    False
Name: score, dtype: bool

In [5]:
df[df['score'] > 65]                      # rows where score > 65

   name  score
0   Ram     70
1  Sita     85

In [6]:
df[(df['score'] > 60) & (df['score'] < 90)]  # multiple conditions (& and |, not "and"/"or")

   name  score
0   Ram     70
1  Sita     85

**Pattern	and Meaning**

df[df['col'] > x]	---Filter rows by condition
& | ~	AND / OR / NOT for combining conditions

df['col'].isin([...])	---Filter by membership in a list

df['col'].between(a, b)	---Filter by range

**Exercise**

Using the same df from section 3:

1. Get all rows where score is above 70.

2. Get all rows where name is either 'Ram' or 'Gita'.

3. Get all rows where score is between 60 and 85 inclusive.

In [7]:
# 1
df[df['score'] > 70]

   name  score
1  Sita     85

In [8]:
# 2
df[df['name'].isin(['Ram', 'Gita'])]

  name  score
0  Ram     70

In [9]:
# 3
df[df['score'].between(60, 85)]

   name  score
0   Ram     70
1  Sita     85
2  Hari     60

**5. Handling Missing Data**

Concept: Real datasets have gaps, represented as NaN. Pandas gives tools to detect, remove, or fill these gaps rather than crashing on them.

In [13]:
import pandas as pd
import numpy as np

In [14]:
df = pd.DataFrame({'a': [1, np.nan, 3], 'b': [4, 5, np.nan]})

In [15]:
df.isna()             # True/False mask of missing values

       a      b
0  False  False
1   True  False
2  False   True

In [16]:
df.isna().sum()       # count of missing values per column

a    1
b    1
dtype: int64

In [17]:
df.dropna()           # drop rows with any NaN

     a    b
0  1.0  4.0

In [18]:
df.fillna(0)          # replace NaN with 0

     a    b
0  1.0  4.0
1  0.0  5.0
2  3.0  0.0

In [19]:
df['a'].fillna(df['a'].mean())   # fill with column mean

0    1.0
1    2.0
2    3.0
Name: a, dtype: float64

**Key operations:**

**Function	Purpose**

.isna() / .isnull()	---Detect missing values

.dropna()	---Remove rows/columns with missing values

.fillna(value)	---Replace missing values

.fillna(method='ffill')	---Fill using previous valid value

**Exercise**

1. Create a DataFrame with at least 2 missing values and count them per column.

2. Drop all rows containing any missing value.

3. Instead of dropping, fill missing values in one column with that column's mean.

In [20]:
df = pd.DataFrame({'x': [1, np.nan, 3, 4], 'y': [np.nan, 2, 3, 4]})

In [21]:
# 1
df.isna().sum()

x    1
y    1
dtype: int64

In [22]:
# 2
df.dropna()

     x    y
2  3.0  3.0
3  4.0  4.0

In [23]:
# 3
df['x'].fillna(df['x'].mean())

0    1.000000
1    2.666667
2    3.000000
3    4.000000
Name: x, dtype: float64